# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UiForm/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 744)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 744))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgView_3 = QtWidgets.QLabel(self.centralwidget)
        self.imgView_3.setGeometry(QtCore.QRect(500, 0, 500, 350))
        self.imgView_3.setFrameShape(QtWidgets.QFrame.Box)
        self.imgView_3.setText("")
        self.imgView_3.setAlignment(QtCore.Qt.AlignCenter)
        self.imgView_3.setObjectName("imgView_3")
        self.imgView_1 = QtWidgets.QLabel(self.centralwidget)
        self.imgView_1.setGeometry(QtCore.QRect(0, 350, 500, 350))
        self.imgView_1.setFrameShape(QtWidgets.QFrame.Box)
        self.imgView_1.setLineWidth(1)
        self.imgView_1.setText("")
        self.imgView_1.setAlignment(QtCore.Qt.AlignCenter)
        self.imgView_1.setObjectName("imgView_1")
        self.imgView_2 = QtWidgets.QLabel(self.centralwidget)
        self.imgView_2.setGeometry(QtCore.QRect(500, 350, 500, 350))
        self.imgView_2.setFrameShape(QtWidgets.QFrame.Box)
        self.imgView_2.setText("")
        self.imgView_2.setAlignment(QtCore.Qt.AlignCenter)
        self.imgView_2.setObjectName("imgView_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 500, 350))
        self.treeWidget.setLineWidth(3)
        self.treeWidget.setTabKeyNavigation(False)
        self.treeWidget.setProperty("showDropIndicator", True)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./UiForm/../../icons/blue-folder-horizontal-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Image.setIcon(icon)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionRemove_Image = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./UiForm/../../icons/cross-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_Image.setIcon(icon1)
        self.actionRemove_Image.setObjectName("actionRemove_Image")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./UiForm/../../icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_All_Images = QtWidgets.QAction(MainWindow)
        self.actionSave_All_Images.setObjectName("actionSave_All_Images")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./UiForm/../../icons/if_logout_48698.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./UiForm/../../icons/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon4)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_the_Authors = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./UiForm/../../icons/if_hire-me_48687.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_the_Authors.setIcon(icon5)
        self.actionAbout_the_Authors.setObjectName("actionAbout_the_Authors")
        self.actionAbout_the_App = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./UiForm/../../icons/if_special-offer_48729.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_the_App.setIcon(icon6)
        self.actionAbout_the_App.setObjectName("actionAbout_the_App")
        self.menuFile.addAction(self.actionLoad_Image)
        self.menuFile.addAction(self.actionRemove_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionHelp)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionAbout_the_Authors)
        self.menuOptions.addAction(self.actionAbout_the_App)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Malik-Images"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image"))
        self.actionLoad_Image.setStatusTip(_translate("MainWindow", "Load New Image..."))
        self.actionLoad_Image.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionRemove_Image.setText(_translate("MainWindow", "Remove Image"))
        self.actionRemove_Image.setStatusTip(_translate("MainWindow", "Remove image..."))
        self.actionRemove_Image.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSave.setText(_translate("MainWindow", "Save Image"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save a selected image"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_All_Images.setText(_translate("MainWindow", "Save All Images"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Close the program"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout_the_Authors.setText(_translate("MainWindow", "About the Authors"))
        self.actionAbout_the_App.setText(_translate("MainWindow", "About the App"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
