# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UiForm/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 744))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./UiForm/../../icons/logo_large.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 300, 731))
        self.treeWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.treeWidget.setLineWidth(3)
        self.treeWidget.setTabKeyNavigation(False)
        self.treeWidget.setProperty("showDropIndicator", True)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(320, 14, 640, 360))
        font = QtGui.QFont()
        font.setFamily("UnBatang")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setObjectName("groupBox_1")
        self.plusImage_1 = QtWidgets.QCommandLinkButton(self.groupBox_1)
        self.plusImage_1.setGeometry(QtCore.QRect(530, 270, 30, 30))
        self.plusImage_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./UiForm/../../icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plusImage_1.setIcon(icon1)
        self.plusImage_1.setObjectName("plusImage_1")
        self.minusImage_1 = QtWidgets.QCommandLinkButton(self.groupBox_1)
        self.minusImage_1.setGeometry(QtCore.QRect(380, 240, 30, 30))
        self.minusImage_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./UiForm/../../icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minusImage_1.setIcon(icon2)
        self.minusImage_1.setIconSize(QtCore.QSize(15, 15))
        self.minusImage_1.setObjectName("minusImage_1")
        self.showImage_1 = QtWidgets.QCommandLinkButton(self.groupBox_1)
        self.showImage_1.setGeometry(QtCore.QRect(80, 240, 30, 30))
        self.showImage_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./UiForm/../../icons/no-hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showImage_1.setIcon(icon3)
        self.showImage_1.setIconSize(QtCore.QSize(15, 15))
        self.showImage_1.setObjectName("showImage_1")
        self.imgView_1 = QtWidgets.QLabel(self.groupBox_1)
        self.imgView_1.setEnabled(True)
        self.imgView_1.setGeometry(QtCore.QRect(0, 24, 621, 331))
        self.imgView_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imgView_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imgView_1.setLineWidth(1)
        self.imgView_1.setText("")
        self.imgView_1.setAlignment(QtCore.Qt.AlignCenter)
        self.imgView_1.setObjectName("imgView_1")
        self.scrollArea_1 = QtWidgets.QScrollArea(self.groupBox_1)
        self.scrollArea_1.setGeometry(QtCore.QRect(9, 29, 611, 321))
        self.scrollArea_1.setWidgetResizable(True)
        self.scrollArea_1.setObjectName("scrollArea_1")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 609, 319))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_1.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_1.raise_()
        self.imgView_1.raise_()
        self.minusImage_1.raise_()
        self.plusImage_1.raise_()
        self.showImage_1.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(950, 14, 640, 360))
        font = QtGui.QFont()
        font.setFamily("UnBatang")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.showImage_2 = QtWidgets.QCommandLinkButton(self.groupBox_2)
        self.showImage_2.setGeometry(QtCore.QRect(80, 290, 30, 30))
        self.showImage_2.setText("")
        self.showImage_2.setIcon(icon3)
        self.showImage_2.setIconSize(QtCore.QSize(15, 15))
        self.showImage_2.setObjectName("showImage_2")
        self.imgView_2 = QtWidgets.QLabel(self.groupBox_2)
        self.imgView_2.setGeometry(QtCore.QRect(0, 24, 621, 311))
        self.imgView_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imgView_2.setText("")
        self.imgView_2.setAlignment(QtCore.Qt.AlignCenter)
        self.imgView_2.setObjectName("imgView_2")
        self.minusImage_2 = QtWidgets.QCommandLinkButton(self.groupBox_2)
        self.minusImage_2.setGeometry(QtCore.QRect(550, 290, 30, 30))
        self.minusImage_2.setText("")
        self.minusImage_2.setIcon(icon2)
        self.minusImage_2.setObjectName("minusImage_2")
        self.plusImage_2 = QtWidgets.QCommandLinkButton(self.groupBox_2)
        self.plusImage_2.setGeometry(QtCore.QRect(590, 290, 30, 30))
        self.plusImage_2.setText("")
        self.plusImage_2.setIcon(icon1)
        self.plusImage_2.setObjectName("plusImage_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(110, 130, 120, 80))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 118, 78))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.imgView_2.raise_()
        self.scrollArea_2.raise_()
        self.showImage_2.raise_()
        self.plusImage_2.raise_()
        self.minusImage_2.raise_()
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 380, 640, 360))
        font = QtGui.QFont()
        font.setFamily("UnBatang")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.imgView_3 = QtWidgets.QLabel(self.groupBox_3)
        self.imgView_3.setGeometry(QtCore.QRect(0, 24, 611, 351))
        self.imgView_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imgView_3.setText("")
        self.imgView_3.setAlignment(QtCore.Qt.AlignCenter)
        self.imgView_3.setObjectName("imgView_3")
        self.showImage_3 = QtWidgets.QCommandLinkButton(self.groupBox_3)
        self.showImage_3.setGeometry(QtCore.QRect(30, 290, 30, 30))
        self.showImage_3.setText("")
        self.showImage_3.setIcon(icon3)
        self.showImage_3.setIconSize(QtCore.QSize(15, 15))
        self.showImage_3.setObjectName("showImage_3")
        self.minusImage_3 = QtWidgets.QCommandLinkButton(self.groupBox_3)
        self.minusImage_3.setGeometry(QtCore.QRect(550, 300, 30, 30))
        self.minusImage_3.setText("")
        self.minusImage_3.setIcon(icon2)
        self.minusImage_3.setObjectName("minusImage_3")
        self.plusImage_3 = QtWidgets.QCommandLinkButton(self.groupBox_3)
        self.plusImage_3.setGeometry(QtCore.QRect(580, 300, 30, 30))
        self.plusImage_3.setText("")
        self.plusImage_3.setIcon(icon1)
        self.plusImage_3.setObjectName("plusImage_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.groupBox_3)
        self.scrollArea_3.setGeometry(QtCore.QRect(330, 110, 120, 80))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 118, 78))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.imgView_3.raise_()
        self.scrollArea_3.raise_()
        self.plusImage_3.raise_()
        self.minusImage_3.raise_()
        self.showImage_3.raise_()
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(950, 380, 640, 360))
        font = QtGui.QFont()
        font.setFamily("UnBatang")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.imgView_4 = QtWidgets.QLabel(self.groupBox_4)
        self.imgView_4.setGeometry(QtCore.QRect(20, 50, 591, 321))
        self.imgView_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imgView_4.setText("")
        self.imgView_4.setAlignment(QtCore.Qt.AlignCenter)
        self.imgView_4.setObjectName("imgView_4")
        self.showImage_4 = QtWidgets.QCommandLinkButton(self.groupBox_4)
        self.showImage_4.setGeometry(QtCore.QRect(120, 280, 30, 30))
        self.showImage_4.setText("")
        self.showImage_4.setIcon(icon3)
        self.showImage_4.setIconSize(QtCore.QSize(15, 15))
        self.showImage_4.setObjectName("showImage_4")
        self.minusImage_4 = QtWidgets.QCommandLinkButton(self.groupBox_4)
        self.minusImage_4.setGeometry(QtCore.QRect(530, 280, 30, 30))
        self.minusImage_4.setText("")
        self.minusImage_4.setIcon(icon2)
        self.minusImage_4.setObjectName("minusImage_4")
        self.plusImage_4 = QtWidgets.QCommandLinkButton(self.groupBox_4)
        self.plusImage_4.setGeometry(QtCore.QRect(570, 270, 30, 30))
        self.plusImage_4.setText("")
        self.plusImage_4.setIcon(icon1)
        self.plusImage_4.setObjectName("plusImage_4")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.groupBox_4)
        self.scrollArea_4.setGeometry(QtCore.QRect(100, 80, 120, 80))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 118, 78))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.imgView_4.raise_()
        self.scrollArea_4.raise_()
        self.plusImage_4.raise_()
        self.minusImage_4.raise_()
        self.showImage_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuFilter = QtWidgets.QMenu(self.menubar)
        self.menuFilter.setObjectName("menuFilter")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./UiForm/../../icons/blue-folder-horizontal-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Image.setIcon(icon4)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionRemove_Image = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./UiForm/../../icons/cross-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_Image.setIcon(icon5)
        self.actionRemove_Image.setObjectName("actionRemove_Image")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./UiForm/../../icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon6)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_All_Images = QtWidgets.QAction(MainWindow)
        self.actionSave_All_Images.setObjectName("actionSave_All_Images")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./UiForm/../../icons/if_logout_48698.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon7)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./UiForm/../../icons/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon8)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_the_Authors = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("./UiForm/../../icons/if_hire-me_48687.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_the_Authors.setIcon(icon9)
        self.actionAbout_the_Authors.setObjectName("actionAbout_the_Authors")
        self.actionAbout_the_App = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("./UiForm/../../icons/if_special-offer_48729.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_the_App.setIcon(icon10)
        self.actionAbout_the_App.setObjectName("actionAbout_the_App")
        self.actionAnisotropic_Diffusion = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("./UiForm/../../icons/lifebuoy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnisotropic_Diffusion.setIcon(icon11)
        self.actionAnisotropic_Diffusion.setObjectName("actionAnisotropic_Diffusion")
        self.actionImages_Tree = QtWidgets.QAction(MainWindow)
        self.actionImages_Tree.setCheckable(True)
        self.actionImages_Tree.setChecked(True)
        self.actionImages_Tree.setObjectName("actionImages_Tree")
        self.actionOrientation = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("./UiForm/../../icons/clipboard-paste-document-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOrientation.setIcon(icon12)
        self.actionOrientation.setObjectName("actionOrientation")
        self.actionReport = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("./UiForm/../../icons/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport.setIcon(icon13)
        self.actionReport.setObjectName("actionReport")
        self.actionView_GIF = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("./UiForm/../../icons/application-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionView_GIF.setIcon(icon14)
        self.actionView_GIF.setObjectName("actionView_GIF")
        self.menuFile.addAction(self.actionLoad_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRemove_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionHelp)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionOrientation)
        self.menuOptions.addAction(self.actionReport)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionAbout_the_Authors)
        self.menuOptions.addAction(self.actionAbout_the_App)
        self.menuFilter.addAction(self.actionAnisotropic_Diffusion)
        self.menuFilter.addAction(self.actionView_GIF)
        self.menuView.addAction(self.actionImages_Tree)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Anisotropic Diffusion"))
        self.treeWidget.setStatusTip(_translate("MainWindow", "Image Tree"))
        self.groupBox_1.setStatusTip(_translate("MainWindow", "Normal Image"))
        self.groupBox_1.setTitle(_translate("MainWindow", "Normal"))
        self.plusImage_1.setStatusTip(_translate("MainWindow", "Zoom Image"))
        self.minusImage_1.setStatusTip(_translate("MainWindow", "Minus Image"))
        self.showImage_1.setStatusTip(_translate("MainWindow", "Show Image"))
        self.groupBox_2.setStatusTip(_translate("MainWindow", "Normal-2 Image"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Normal-2"))
        self.showImage_2.setStatusTip(_translate("MainWindow", "Show Image"))
        self.minusImage_2.setStatusTip(_translate("MainWindow", "Minus Image"))
        self.plusImage_2.setStatusTip(_translate("MainWindow", "Zoom Image"))
        self.groupBox_3.setStatusTip(_translate("MainWindow", "Edge Image"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Edge"))
        self.showImage_3.setStatusTip(_translate("MainWindow", "Show Image"))
        self.minusImage_3.setStatusTip(_translate("MainWindow", "Minus Image"))
        self.plusImage_3.setStatusTip(_translate("MainWindow", "Zoom Image"))
        self.groupBox_4.setStatusTip(_translate("MainWindow", "AD-Edge Image"))
        self.groupBox_4.setTitle(_translate("MainWindow", "AD-Edge"))
        self.showImage_4.setStatusTip(_translate("MainWindow", "Show Image"))
        self.minusImage_4.setStatusTip(_translate("MainWindow", "Minus Image"))
        self.plusImage_4.setStatusTip(_translate("MainWindow", "Zoom Image"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuFilter.setTitle(_translate("MainWindow", "Filter"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image"))
        self.actionLoad_Image.setStatusTip(_translate("MainWindow", "Load New Image..."))
        self.actionLoad_Image.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionRemove_Image.setText(_translate("MainWindow", "Remove Image"))
        self.actionRemove_Image.setStatusTip(_translate("MainWindow", "Remove image..."))
        self.actionRemove_Image.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSave.setText(_translate("MainWindow", "Save Image"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save a selected image"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_All_Images.setText(_translate("MainWindow", "Save All Images"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Close the program"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+F4"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setStatusTip(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout_the_Authors.setText(_translate("MainWindow", "About the Authors"))
        self.actionAbout_the_Authors.setStatusTip(_translate("MainWindow", "About the Authors"))
        self.actionAbout_the_Authors.setShortcut(_translate("MainWindow", "F9"))
        self.actionAbout_the_App.setText(_translate("MainWindow", "About the App"))
        self.actionAbout_the_App.setStatusTip(_translate("MainWindow", "About the App"))
        self.actionAbout_the_App.setShortcut(_translate("MainWindow", "F10"))
        self.actionAnisotropic_Diffusion.setText(_translate("MainWindow", "Anisotropic Diffusion"))
        self.actionAnisotropic_Diffusion.setStatusTip(_translate("MainWindow", "Anisotropic Diffusion"))
        self.actionAnisotropic_Diffusion.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionImages_Tree.setText(_translate("MainWindow", "Image Tree"))
        self.actionImages_Tree.setStatusTip(_translate("MainWindow", "Hidde Image Tree"))
        self.actionImages_Tree.setShortcut(_translate("MainWindow", "F3"))
        self.actionOrientation.setText(_translate("MainWindow", "Orientation"))
        self.actionOrientation.setShortcut(_translate("MainWindow", "F5"))
        self.actionReport.setText(_translate("MainWindow", "Report"))
        self.actionReport.setShortcut(_translate("MainWindow", "F6"))
        self.actionView_GIF.setText(_translate("MainWindow", "View GIF"))
        self.actionView_GIF.setShortcut(_translate("MainWindow", "Ctrl+V"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
