# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UiForm/parameters.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(484, 291)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(280, 240, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 80, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(260, 70, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(270, 130, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(100, 20, 21, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.sigmaSpin = QtWidgets.QSpinBox(Dialog)
        self.sigmaSpin.setGeometry(QtCore.QRect(160, 80, 50, 30))
        self.sigmaSpin.setObjectName("sigmaSpin")
        self.iterationSpin = QtWidgets.QSpinBox(Dialog)
        self.iterationSpin.setGeometry(QtCore.QRect(370, 10, 48, 30))
        self.iterationSpin.setObjectName("iterationSpin")
        self.updbSpin = QtWidgets.QDoubleSpinBox(Dialog)
        self.updbSpin.setGeometry(QtCore.QRect(140, 130, 69, 30))
        self.updbSpin.setObjectName("updbSpin")
        self.updfSpin = QtWidgets.QDoubleSpinBox(Dialog)
        self.updfSpin.setGeometry(QtCore.QRect(350, 130, 69, 30))
        self.updfSpin.setObjectName("updfSpin")
        self.constSpin = QtWidgets.QSpinBox(Dialog)
        self.constSpin.setGeometry(QtCore.QRect(160, 20, 48, 30))
        self.constSpin.setObjectName("constSpin")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.edgeBox = QtWidgets.QComboBox(Dialog)
        self.edgeBox.setGeometry(QtCore.QRect(140, 190, 91, 30))
        self.edgeBox.setObjectName("edgeBox")
        self.edgeBox.addItem("")
        self.edgeBox.addItem("")
        self.edgeBox.addItem("")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(260, 10, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.clusterSpin = QtWidgets.QSpinBox(Dialog)
        self.clusterSpin.setGeometry(QtCore.QRect(370, 70, 48, 30))
        self.clusterSpin.setObjectName("clusterSpin")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Parameters"))
        self.label.setText(_translate("Dialog", "Sigma"))
        self.label_2.setText(_translate("Dialog", "Clusters"))
        self.label_3.setText(_translate("Dialog", "UPDB"))
        self.label_4.setText(_translate("Dialog", "UPDF"))
        self.label_5.setText(_translate("Dialog", "h"))
        self.label_6.setText(_translate("Dialog", "Edges Type"))
        self.edgeBox.setItemText(0, _translate("Dialog", "Scharr"))
        self.edgeBox.setItemText(1, _translate("Dialog", "Canny"))
        self.edgeBox.setItemText(2, _translate("Dialog", "Sobel"))
        self.label_7.setText(_translate("Dialog", "Iteration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
